BaseURL = "https://bivectorfoil.github.io/"
LanguageCode = "zh-CN"
HasCJKLanguage = true
Title = "Zvector & Blog"
Theme = "hugo-pacman-theme"
pygmentsStyle = "default"
pygmentsUseClasses = true
buildDrafts = false


[Author]
  Name = "zvector"

[outputs]
  home = [ "RSS", "HTML" ]

[Params]
  AuthorHomepage = "https://bivectorfoil.github.io/"
  BottomIntroduce = "Connect the world <br/> Learn the world"
  # you world rather to do nothing than something?
  Description = ""
  Subtitle = "Connect the world"
  GitHub = "Bivectorfoil"
  Imglogo = "img/logo.svg"
  AuthorImg = "img/author.jpg"
  # 日期时间格式
  DateFormat = "2006年01月02日"
  MonthFormat = "2006年01月"
  FancyBox = true
  CreativeCommons = true

  # 使用 Disqus 评论
  [Params.Disqus]
    ShortName = "zvector"

  # Google 统计
  #[Params.GoogleAnalytics]
  #  ID = "UA-10147768-2"

  # 多语言字符串
  [Params.Strings]
    Search = "搜索"
    PageNotFound = "你访问的页面不存在"
    ShowSideBar = "显示侧边栏"
    HideSideBar = "隐藏侧边栏"
    Categories = "分类"
    Archive = "归档"
    Tags = "标签"
    TagCloud = "标签云"
    TableOfContents = "文章目录"

[Menu]
  [[Menu.Main]]
    Name = "首页"
    URL = "/"
    Weight = 1
  [[Menu.Main]]
    Name = "关于"
    URL = "/about"
    Weight = 2
